# Generated by Django 5.2.4 on 2025-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstage',
            name='failure_reaction',
            field=models.TextField(default='', help_text='失敗時の川田の反応'),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='mock_result_json',
            field=models.TextField(blank=True, default='{}', help_text='模擬実行結果（JSON形式）'),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='sample_data_json',
            field=models.TextField(default='[]', help_text='サンプルデータ（JSON形式）'),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='story_text',
            field=models.TextField(default='', help_text='ステージのストーリー・背景'),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='success_reaction',
            field=models.TextField(default='', help_text='成功時の川田の反応'),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='table_name',
            field=models.CharField(default='', help_text='サンプルテーブル名', max_length=100),
        ),
    ]
