# Generated by Django 5.2.4 on 2025-07-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlquiz', '0002_quizstage_failure_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstage',
            name='alternative_solutions_json',
            field=models.TextField(default='[]', help_text='代替正解パターン（JSON配列）'),
        ),
    ]
