# Generated by Django 5.2.4 on 2025-08-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstudystats',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={},
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='completed',
        ),
        migrations.AlterField(
            model_name='studysession',
            name='app_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='lesson_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('encouragement', '励まし'), ('reminder', 'リマインダー'), ('congratulations', 'お祝い'), ('invitation', 'お誘い'), ('welcome_back', '復帰歓迎')], max_length=20, verbose_name='メッセージ種別')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '川田からのメッセージ',
                'verbose_name_plural': '川田からのメッセージ',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='学習内容')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(verbose_name='終了日時')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学習スケジュール',
                'verbose_name_plural': '学習スケジュール',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sessions', models.IntegerField(default=0, verbose_name='完了セッション数')),
                ('total_hours', models.FloatField(default=0.0, verbose_name='合計学習時間')),
                ('current_streak', models.IntegerField(default=0, verbose_name='現在の継続日数')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='最長の継続日数')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='最終学習日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー統計',
                'verbose_name_plural': 'ユーザー統計',
            },
        ),
        migrations.DeleteModel(
            name='KawadaMessage',
        ),
        migrations.DeleteModel(
            name='StudySchedule',
        ),
        migrations.DeleteModel(
            name='UserStudyStats',
        ),
    ]
