# Generated by Django 5.2.4 on 2025-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLessonSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text='スクロール位置 (px)')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('type', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('explanation', 'Explanation'), ('warning', 'Warning Quiz')], default='text', max_length=20)),
                ('content', models.TextField(help_text='表示内容')),
                ('kawada_emotion', models.CharField(choices=[('default', 'Default'), ('cheerful', 'Cheerful'), ('gentle', 'Gentle'), ('thinking', 'Thinking'), ('smile', 'Smile')], default='default', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='表示順序')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='問題文')),
                ('options', models.JSONField(help_text='選択肢（JSON配列）')),
                ('correct_answer', models.IntegerField(help_text='正解番号（0から開始）')),
                ('explanation', models.TextField(help_text='解説')),
                ('kawada_correct_message', models.CharField(default='川田、正解です！', max_length=200)),
                ('kawada_wrong_message', models.CharField(default='川田、もう一度考えてみましょう', max_length=200)),
                ('trigger_position', models.IntegerField(help_text='問題表示位置 (px)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
